# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAudioKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  source 'https://github.com/AudioKit/Specs.git'
  source 'https://cdn.cocoapods.org/'

  # Pods for TestAudioKit

  pod 'AudioKit', '=5.0.b1'

end
