# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestRetainCycle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestRetainCycle
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa', '~> 5.1'

  target 'TestRetainCycleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
